version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-stretch-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            wget https://github.com/allure-framework/allure2/releases/download/2.7.0/allure-2.7.0.zip
            unzip allure-2.7.0.zip
            export PATH=$PATH:/home/circleci/repo/allure-2.7.0/bin
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            chmod 755 ./Phase4/chromedriver/chromedriver
            pytest -v --ignore Phase1 --ignore Phase2 --ignore Phase3 --ignore Phase4 --driver Chrome --driver-path ./Phase4/chromedriver/chromedriver --alluredir ./pytest-reports ./allure-2.7.0/bin/allure generate generate
      - store_artifacts:
          path: allure-reports
          destination: allure-reports