version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-stretch-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            wget https://github.com/allure-framework/allure2/releases/download/2.7.0/allure-2.7.0.zip
            unzip allure-2.7.0.zip
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            chmod -R 777 ./Phase5/chromedriver
            chmod -R 777 ./allure-2.7.0/bin/
            cd ./Phase5
            ls
            pytest -v --driver Chrome --driver-path ./chromedriver/chromedriver --alluredir=./pytest_report
            cd ..
            ./allure-2.7.0/bin/allure generate -c ./Phase5/pytest_report  
      - store_artifacts:
          path: allure-reports
          destination: allure-reports